language: python
python:
    - "3.5"
addons:
  apt:
    packages:
      - graphviz
before_install:
    - openssl aes-256-cbc -K $encrypted_8e28d6063879_key -iv $encrypted_8e28d6063879_iv -in sage_interactions.enc -out ~/.ssh/publish-key -d
    - pip install nbformat ipython
    - python helpers/gen_req_txt_from_notebooks.py --nbs_dir=. --req_txt_fname=helpers/requirements.txt
install:
    - pip install nbval
    - pip install ghp-import
    - pip install -r helpers/requirements.txt
script:
    - py.test --nbval-lax *.ipynb
    - git clone https://github.com/christianp/jupyter-interactions-site
    - cp jupyter-interactions-site/config.yml.dist jupyter-interactions-site/config.yml
    - sed -i s#http://localhost:8888/notebooks/jupyter-interactions/#https://github.com/mikecroucher/jupyter-interactions/blob/master/# jupyter-interactions-site/config.yml
    - sed -i s#notebook_path: ../jupyter-interactions#notebook_path: ../# jupyter-interactions-site/config.yml
    - pip install -r jupyter-interactions-site/requirements.txt
    - cd jupyter-interactions-site
    - python build_site.py
    - chmod u=rw,og= ~/.ssh/publish-key
    - echo "Host github.com" >> ~/.ssh/config
    - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
    - git remote set-url origin git@github.com:mikecroucher/jupyter-interactions
    - git fetch origin -f gh-pages:gh-pages
    - ghp-import -n -p -m "Update gh-pages." ./site
